name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13.5'
      - name: Встановлення залежностей
        run: pip install -r requirements.txt
      - name: Перевірка PEP8 (flake8)
        run: flake8 main.py test_filter.py
      - name: Запуск тестів зі звітом HTML
        run: pytest test_filter.py --html=report.html --self-contained-html